#!/usr/bin/env python
# Nginx Admin Installer
# Website: www.nginxcp.com
#
# Copyright (C) NGINXCP.COM.
#
import subprocess
import sys
import os
import yaml
from xml.dom import minidom
sys.path.append('/scripts')
import createvhosts
doc = minidom.parse(sys.stdin)

resulttaglist = doc.getElementsByTagName('result')
resultlist =[]

if resulttaglist[1].childNodes[0].toxml() == 0:
        sys.exit
else:
        subdomaintaglist = doc.getElementsByTagName('subdomain')
        subdomain = subdomaintaglist[0].childNodes[0].toxml()
        maindomaintaglist = doc.getElementsByTagName('DOMAIN')
        maindomain = maindomaintaglist[0].childNodes[0].toxml()
        domain =  subdomain + '.' + maindomain
        usertaglist = doc.getElementsByTagName('USER')
        user = usertaglist[0].childNodes[0].toxml()
        docroot, yip, alias = createvhosts.getvars(domain)
        serverip = createvhosts.getmainip()
if yip == "":
    sys.exit()
if yip == serverip:
        createvhosts.writeconfshared(user, domain, docroot, yip, alias)
else:
	createvhosts.writeconfded(user, domain, docroot, yip, alias)
        proc = subprocess.Popen("/etc/init.d/nginx restart > /dev/null 2>&1", shell=True)


