#!/usr/bin/env python
import sys
import subprocess
import os
import yaml
from xml.dom import minidom
sys.path.append('/scripts')
import createvhosts

doc = minidom.parse(sys.stdin)

subtaglist = doc.getElementsByTagName('domain')
sublist = []
subdomain = subtaglist[0].childNodes[0].toxml()
subdomain2 = subdomain.replace('_','.')
proc = subprocess.Popen("rm -f /etc/nginx/vhosts/" + subdomain2, shell=True)
proc = proc = subprocess.Popen("/etc/init.d/nginx restart > /dev/null 2>&1", shell=True)
