#!/bin/sh

NGINX_IPV=n
CUSTOMSERVERNAME='n'
CUSTOMSERVERSTRING='nginx admin'

HN=$(uname -n)

# compiler related
CLANG='n'                     # Nginx and LibreSSL
NGINX_HTTP2=y                # Nginx http/2 patch https://community.centminmod.com/threads/4127/
NGINX_SPDY=n                 # Nginx SPDY support
NGINX_FLV=y                  # http://nginx.org/en/docs/http/ngx_http_flv_module.html
NGINX_MP4=y                  # Nginx MP4 Module http://nginx.org/en/docs/http/ngx_http_mp4_module.html
NGINX_VHOSTSTATS=n           # https://github.com/vozlt/nginx-module-vts
NGINX_PCREJIT=y              # Nginx configured with pcre & pcre-jit support
NGINX_PCREVER='8.37'         # Version of PCRE used for pcre-jit support in Nginx

##################################
## Nginx SSL options
# OpenSSL
OPENSSL_VERSION='1.0.2d'   # Use this version of OpenSSL http://openssl.org/

# LibreSSL
LIBRESSL_SWITCH='n'        # if set to 'y' it overrides OpenSSL as the default static compiled option for Nginx server
LIBRESSL_VERSION='2.2.4'   # Use this version of LibreSSL http://www.libressl.org/
##################################

function funct_nginxconfigure {

	if [[ "$NGINX_HTTP2" = [yY] ]]; then	
			NGINX_SPDY=n		
			HTTPTWOOPT=' --with-http_v2_module'
	fi
	else
		HTTPTWOOPT=""
	fi

	if [[ "$LIBRESSL_SWITCH" = [yY] ]]; then
		LIBRESSLOPT=" --with-openssl=../libressl-${LIBRESSL_VERSION}"
		OPENSSLOPT=""
		LRT='-lrt '
	fi
	else
			LIBRESSLOPT=""
			OPENSSLOPT=" --with-openssl=../openssl-${OPENSSL_VERSION}"
			LRT=""

	fi

	if [[ "$NGINX_SPDY" = [yY] ]]; then
		SPDYOPT=" --with-http_spdy_module"
		HTTPTWOOPT=""
	else
	    NGINX_HTTP2=n
		SPDYOPT=""
	fi
	
	if [[ "$NGINX_FLV" = [yY] ]]; then
		FLVOPT=" --with-http_flv_module"
	else
		FLVOPT=""
	fi
	
	if [[ "$NGINX_MP4" = [yY] ]]; then
		MPOPT=" --with-http_mp4_module"
	else
		MPOPT=""
	fi		
	
	if [[ "$NGINX_VHOSTSTATS" = [yY] ]]; then
		if [ -f /usr/bin/git ]; then
			VTSOPT=" --add-module=../nginx-module-vts"
			if [[ ! -d "${DIR_TMP}/nginx-module-vts" ]]; then
				cd $DIR_TMP
				git clone $NGX_VTSLINK nginx-module-vts
				# sed -i 's|color:       black;|color:       white;|g' ${DIR_TMP}/nginx-module-vts/share/status.template.html
				sed -i 's|#DED|#43a6df|g' ${DIR_TMP}/nginx-module-vts/share/status.template.html
				# sed -i 's|color:       black;|color:       white;|g' ${DIR_TMP}/nginx-module-vts/share/status.compress.html
				sed -i 's|#DED|#43a6df|g' ${DIR_TMP}/nginx-module-vts/share/status.compress.html
				cd nginx-module-vts/util
				./tplToDefine.sh ../share/status.template.html > ../src/ngx_http_vhost_traffic_status_module_html.h
				# ./tplToDefine.sh ../share/status.compress.html > ../src/ngx_http_vhost_traffic_status_module_html.h
				cd ../
				# setup /vhost_status.html
				cp -a ${DIR_TMP}/nginx-module-vts/share/status.compress.html /usr/local/nginx/html/vhost_status.html
				MAINURIHOST=$HN
				NEWURI="//${MAINURIHOST}/vhost_status"
				if [ -f /usr/local/nginx/html/vhost_status.html ]; then
					sed -i "s|{{uri}}|$NEWURI|" /usr/local/nginx/html/vhost_status.html
				fi
			elif [[ -d "${DIR_TMP}/nginx-module-vts" && -d "${DIR_TMP}/nginx-module-vts/.git" ]]; then
				cd ${DIR_TMP}/nginx-module-vts
				git stash
				git pull
				# sed -i 's|color:       black;|color:       white;|g' ${DIR_TMP}/nginx-module-vts/share/status.template.html
				sed -i 's|#DED|#43a6df|g' ${DIR_TMP}/nginx-module-vts/share/status.template.html
				# sed -i 's|color:       black;|color:       white;|g' ${DIR_TMP}/nginx-module-vts/share/status.compress.html
				sed -i 's|#DED|#43a6df|g' ${DIR_TMP}/nginx-module-vts/share/status.compress.html
				cd nginx-module-vts/util
				./tplToDefine.sh ../share/status.template.html > ../src/ngx_http_vhost_traffic_status_module_html.h
				# ./tplToDefine.sh ../share/status.compress.html > ../src/ngx_http_vhost_traffic_status_module_html.h
				cd ../
				# setup /vhost_status.html
				cp -a ${DIR_TMP}/nginx-module-vts/share/status.compress.html /usr/local/nginx/html/vhost_status.html
				MAINURIHOST=$HN
				NEWURI="//${MAINURIHOST}/vhost_status"
				if [ -f /usr/local/nginx/html/vhost_status.html ]; then
					sed -i "s|{{uri}}|$NEWURI|" /usr/local/nginx/html/vhost_status.html
				fi
			fi
		else
			VTSOPT=""
		fi
	else
		VTSOPT=""
	fi
	
	if [[ "$NGINX_PCREJIT" = [yY] ]]; then
		PCREJITOPT=" --with-pcre=../pcre-${NGINX_PCREVER} --with-pcre-jit"
	else
		PCREJITOPT=""
	fi

# intel specific
CPUVENDOR=$(cat /proc/cpuinfo | awk '/vendor_id/ {print $3}' | sort -u | head -n1)
gcc -c -Q -march=native --help=target | egrep '\[enabled\]|mtune|march' | tee ${CENTMINLOGDIR}/gcc_native.log
if [[ "$(uname -m)" = 'x86_64' && "$CPUVENDOR" = 'GenuineIntel' ]]; then
	CCM=64
	MTUNEOPT="-m${CCM} -mtune=native "
elif [[ "$(uname -m)" != 'x86_64' && "$CPUVENDOR" = 'GenuineIntel' ]]; then
	CCM=32
	MTUNEOPT="-m${CCM} -mtune=generic "
else
	MTUNEOPT=""
fi
if [[ "$CLANG" = [yY] ]]; then
	if [[ ! -f /usr/bin/clang ]]; then
		yum -q -y install clang clang-devel
	fi
	if [[ "$INITIALINSTALL" != [yY] ]]; then	
		export CC="/usr/bin/clang -ferror-limit=0"
		export CXX="/usr/bin/clang++ -ferror-limit=0"

		CLANG_CCOPT=' -Wno-deprecated-declarations -Wno-unused-parameter -Wno-unused-const-variable -Wno-conditional-uninitialized -Wno-mismatched-tags -Wno-c++11-extensions -Wno-sometimes-uninitialized -Wno-parentheses-equality -Wno-tautological-compare -Wno-self-assign -Wno-deprecated-register -Wno-deprecated -Wno-invalid-source-encoding -Wno-pointer-sign -Wno-parentheses -Wno-enum-conversion'
	fi
else
	CLANG_CCOPT=""
fi

#    ASK "Would you like to compile nginx with IPv6 support? [y/n] "
#    if [[ "$asknginxipv" = [yY] ]]; then
      if [[ "$NGINX_IPV" = [yY] ]]; then
      	pwd
      	echo "nginx configure options:"
      	echo "./configure --with-ld-opt="${LRT}-ljemalloc -Wl,-z,relro" --with-cc-opt="${MTUNEOPT}-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2${CLANG_CCOPT}" --sbin-path=/usr/local/sbin --conf-path=/etc/nginx/nginx.conf --pid-path=/var/run/nginx.pid --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --with-ipv6 --with-http_ssl_module${HTTPTWOOPT} --http-client-body-temp-path=/tmp/nginx_client --http-proxy-temp-path=/tmp/nginx_proxy --http-fastcgi-temp-path=/tmp/nginx_fastcgi --with-http_stub_status_module${FLVOPT}${MPOPT} --with-http_realip_module --with-openssl-opt="enable-tlsext"${VTSOPT}${OPENSSLOPT}${LIBRESSLOPT}${PCREJITOPT}${SPDYOPT}
		./configure --with-ld-opt="${LRT}-ljemalloc -Wl,-z,relro" --with-cc-opt="${MTUNEOPT}-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2${CLANG_CCOPT}" --sbin-path=/usr/local/sbin --conf-path=/etc/nginx/nginx.conf --pid-path=/var/run/nginx.pid --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --with-ipv6 --with-http_ssl_module${HTTPTWOOPT} --http-client-body-temp-path=/tmp/nginx_client --http-proxy-temp-path=/tmp/nginx_proxy --http-fastcgi-temp-path=/tmp/nginx_fastcgi --with-http_stub_status_module${FLVOPT}${MPOPT} --with-http_realip_module --with-openssl-opt="enable-tlsext"${VTSOPT}${OPENSSLOPT}${LIBRESSLOPT}${PCREJITOPT}${SPDYOPT}
    else
    	pwd
    	echo "nginx configure options:"
    	echo "./configure --with-ld-opt="${LRT}-ljemalloc -Wl,-z,relro" --with-cc-opt="${MTUNEOPT}-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2${CLANG_CCOPT}" --sbin-path=/usr/local/sbin --conf-path=/etc/nginx/nginx.conf --pid-path=/var/run/nginx.pid --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --with-http_ssl_module${HTTPTWOOPT} --http-client-body-temp-path=/tmp/nginx_client --http-proxy-temp-path=/tmp/nginx_proxy --http-fastcgi-temp-path=/tmp/nginx_fastcgi --with-http_stub_status_module${FLVOPT}${MPOPT} --with-http_realip_module --with-openssl-opt="enable-tlsext"${VTSOPT}${OPENSSLOPT}${LIBRESSLOPT}${PCREJITOPT}${SPDYOPT}
		./configure --with-ld-opt="${LRT}-ljemalloc -Wl,-z,relro" --with-cc-opt="${MTUNEOPT}-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2${CLANG_CCOPT}" --sbin-path=/usr/local/sbin --conf-path=/etc/nginx/nginx.conf --pid-path=/var/run/nginx.pid --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --with-http_ssl_module${HTTPTWOOPT} --http-client-body-temp-path=/tmp/nginx_client --http-proxy-temp-path=/tmp/nginx_proxy --http-fastcgi-temp-path=/tmp/nginx_fastcgi --with-http_stub_status_module${FLVOPT}${MPOPT} --with-http_realip_module --with-openssl-opt="enable-tlsext"${VTSOPT}{OPENSSLOPT}${LIBRESSLOPT}${PCREJITOPT}${SPDYOPT}
    fi   
}
